import React from 'react';
import Topbar from '@/src/components/topbar/topbar';
// import Footer from '@/src/components/footer/footer';
import Head from 'next/head';
import Image from 'next/image';
import bg from '@/src/styles/assets/bgcharts.jpg';
import Container from '@mui/material/Container';
import Box from '@mui/material/Box';

import MaterialRiskValue from '@/src/components/charts/MaterialRiskValue';

export default function Home() {
  return (
    <>
      <Head>
        <title>Testing Chart Js</title>
        <meta name="descriptiAon" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
           <Topbar />
            <Image src={bg} alt='bg' fill cover style={{ opacity: '0.2', zIndex: -1}}/>
      </main>
      <section>
          <Container maxWidth='xl'>
            <Box style={{ backgroundColor: '#fff', height: '90vh', width: '105%', marginTop: '-4%', marginLeft: '-3%', display: 'grid', gridTemplateColumns: 'repeat(3,1fr)'}}>
                <Box style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', backgroundColor: '#009add', height: '45vh', marginLeft: '1px', marginRight: '1px', marginBottom: '1px' }}><MaterialRiskValue /></Box>
                <Box style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', backgroundColor: '#419954', height: '45vh', marginLeft: '1px', marginRight: '1px', marginBottom: '1px' }}><MaterialRiskValue /> </Box>
                <Box style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', backgroundColor: '#dd6300', height: '45vh', marginLeft: '1px', marginRight: '1px', marginBottom: '1px' }}><MaterialRiskValue /> </Box>
                <Box style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', backgroundColor: '#d600dd', height: '45vh', marginLeft: '1px', marginRight: '1px', marginBottom: '1px' }}><MaterialRiskValue /> </Box>
                <Box style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', backgroundColor: '#00dd55', height: '45vh', marginLeft: '1px', marginRight: '1px', marginBottom: '1px' }}><MaterialRiskValue /> </Box>
                <Box style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', backgroundColor: '#c7dd00', height: '45vh', marginLeft: '1px', marginRight: '1px', marginBottom: '1px' }}><MaterialRiskValue /> </Box>
            </Box>
          </Container>
      </section>
      {/* <Footer /> */}
    </>
  )
}
